name: tsu
version: develop
version-script: git describe --exact-match --tags 2> /dev/null || echo "develop"
summary: The Tsubaki Smart-Contract Programming-Language
description: |
  Tsubaki is new smart-contract language based on a solidity-superset grammar, 
  providing support for threaded contracts. Existing solidity code is valid Tsubaki 
  code. Tsubaki has been developed for the Lumina blockchain in order to support its
  threaded Lumina Spark transaction model.

grade: stable
confinement: strict

apps:
  tsu:
    command: tsu
    plugs: [home]

parts:
  solidity:
    source: .
    source-type: git
    plugin: cmake
    build-packages: [build-essential, libboost-all-dev, libz3-dev]
    stage-packages: [libicu55]
    prepare: |
      if git describe --exact-match --tags 2> /dev/null
      then
        echo -n > ../src/prerelease.txt
      fi
